# Generated by Django 4.0.4 on 2025-04-14 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentportfolio',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='studentportfolio',
            name='uploaded_by',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
