# Generated by Django 4.0.4 on 2025-04-14 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_studentportfolio_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentportfolio',
            name='parent_comment',
            field=models.TextField(null=True),
        ),
    ]
